OpenH264 upgrade to v2.1.1 via conda-forge
AnacondaRecipes/openh264-feedstock pull request #3
Opened 2021-12-16 12:34 UTC by tobijk

2021-12-17 13:54 UTC, katietz approved these changes

2021-12-17 13:54 UTC, katietz approved these changes

2021-12-17 13:56 UTC, katietz requested changes

2021-12-17 13:56 UTC, katietz commented on .ci_support/linux_aarch64_.yaml
> +- '9'
why those quotes?

2021-12-17 13:56 UTC, katietz commented on .ci_support/linux_aarch64_.yaml
> +- '9'
Likewise

2021-12-17 13:56 UTC, katietz commented on .ci_support/linux_ppc64le_.yaml
> +- '9'
again

2021-12-17 13:56 UTC, katietz commented on .ci_support/linux_ppc64le_.yaml
>  - '1.2'
...

2021-12-18 05:11 UTC, varlackc reviewed
The Dev_url and Doc_url seem to point to the same location.

https://github.com/AnacondaRecipes/openh264-feedstock/blob/update/merge-cf-2.1.1/recipe/meta.yaml#L46&&#L47

maybe we can point to a different location on the doc_url, it might be a good idea to look at the official website:

http://www.openh264.org/

2021-12-20 12:50 UTC, tobijk commented on .ci_support/linux_aarch64_.yaml
> +- '9'
conda-forge specific, closing as informative

2021-12-20 12:50 UTC, tobijk commented on .ci_support/linux_aarch64_.yaml
> +- '9'
conda-forge specific, closing as informative

2021-12-20 12:51 UTC, tobijk commented on .ci_support/linux_ppc64le_.yaml
> +- '9'
conda-forge specific, closing as informative

2021-12-20 12:51 UTC, tobijk commented on .ci_support/linux_ppc64le_.yaml
>  - '1.2'
conda-forge specific, closing as informative

2021-12-20 12:53 UTC, tobijk commented
@varlackc, thanks for the suggestion, there seems to be Doxygen documentation inside the source tree, but unfortunately there isn't a pre-built version of it available anywhere on the homepage. So I think we should leave it as it is.

2021-12-20 12:54 UTC, tobijk commented
Added compatibility symlinks to keep programs linked avainst soversion 5 running. In our repo that is only ffmpeg. I have tested that ffmpeg loads correctly with the symlink in place on linux-64 and osx-64.

2021-12-20 14:28 UTC, katietz approved these changes
lgtm

2021-12-20 15:20 UTC, varlackc approved these changes

2021-12-20 15:32 UTC, merged